"""Operator Zone

Revision ID: 24e4afb71b6a
Revises: 
Create Date: 2020-01-28 09:56:30.535498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24e4afb71b6a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operator_zone', sa.Column('defect_description', sa.String(length=250), nullable=True))
    op.drop_column('operator_zone', 'defect_position')
    op.alter_column('out', 'employee_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('out', 'employee_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('operator_zone', sa.Column('defect_position', sa.VARCHAR(length=250), nullable=True))
    op.drop_column('operator_zone', 'defect_description')
    # ### end Alembic commands ###
