"""Initial migration.

Revision ID: a8be468968be
Revises: 
Create Date: 2020-01-29 10:20:22.093781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8be468968be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operator_zone', sa.Column('defect_description', sa.String(length=250), nullable=True))
    op.drop_constraint(None, 'operator_zone', type_='foreignkey')
    op.drop_column('operator_zone', 'defect_position_id')
    op.alter_column('out', 'employee_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('rework', sa.Column('defect_position', sa.String(length=250), nullable=True))
    op.drop_constraint(None, 'rework', type_='foreignkey')
    op.drop_column('rework', 'defect_position_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rework', sa.Column('defect_position_id', sa.INTEGER(), nullable=False))
    op.create_foreign_key(None, 'rework', 'defect_position', ['defect_position_id'], ['id'])
    op.drop_column('rework', 'defect_position')
    op.alter_column('out', 'employee_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('operator_zone', sa.Column('defect_position_id', sa.INTEGER(), nullable=False))
    op.create_foreign_key(None, 'operator_zone', 'defect_position', ['defect_position_id'], ['id'])
    op.drop_column('operator_zone', 'defect_description')
    # ### end Alembic commands ###
